apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.25.3
    ports:
      - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
